# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'csell_land_map' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    rn_maps_path = '../node_modules/react-native-maps'
    
    pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
    ]

    pod 'SDWebImage', '~>5.0'
    
    pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
    pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
    pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
    pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
    
    pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
    
    pod 'react-native-maps', path: rn_maps_path
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
  
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

    pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'


  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'


  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'


  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        targets_to_ignore = %w(React yoga)
        if targets_to_ignore.include? target.name
            target.remove_from_project
        end
        if target.name == 'react-native-google-maps'
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
            end
        end
    end
end


