export const SHOW_LOADING_MAP = 'SHOW_LOADING_MAP'

export const PUSH_DATA_TO_DETAIL = 'PUSH_DATA_TO_DETAIL'

export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS'
export const CLEAN_LIST_PRODUCT = 'CLEAN_LIST_PRODUCT'

export const GET_PRODUCTS_IN_MAP = 'GET_PRODUCTS_IN_MAP'
export const GET_PRODUCTS_IN_MAP_SUCCESS = 'GET_PRODUCTS_IN_MAP_SUCCESS'
export const GET_PRODUCTS_IN_MAP_FAILURE = 'GET_PRODUCTS_IN_MAP_FAILURE'

export const RESET_POPY_DRAW_IN_MAP = 'RESET_POPY_DRAW_IN_MAP'

export const SHOW_COUNT_NUMBER_FILTER = 'SHOW_COUNT_NUMBER_FILTER'

export const EVENT_CLICK_ITEM_SEARCH_LOCATION = 'EVENT_CLICK_ITEM_SEARCH_LOCATION'
export const EVENT_DELETE_SEARCH_LOCATION = 'EVENT_DELETE_SEARCH_LOCATION'

export const DISABLE_VIEW_LIST_PRODUCT = 'DISABLE_VIEW_LIST_PRODUCT'

export const SEARCH_MAP = 'SEARCH_MAP'
export const SEARCH_MAP_SUCCESS = 'SEARCH_MAP_SUCCESS'
export const SEARCH_MAP_FAILURE = 'SEARCH_MAP_FAILURE'
export const CLEAR_SEARCH_MAP = 'CLEAR_SEARCH_MAP'

export const SEARCH_PROJECTS = 'SEARCH_PROJECTS'
export const SEARCH_PROJECTS_SUCCESS = 'SEARCH_PROJECTS_SUCCESS'
export const SEARCH_PROJECTS_FAILURE = 'SEARCH_PROJECTS_FAILURE'
export const CLEAN_SEARCH_PROJECTS = 'CLEAN_SEARCH_PROJECTS'

export const UPLOAD_IMAGES = 'UPLOAD_IMAGES'
export const UPLOAD_IMAGES_SUCCESS = 'UPLOAD_IMAGES_SUCCESS'
export const UPLOAD_IMAGES_FAILURE = 'UPLOAD_IMAGES_FAILURE'

export const GET_PROJECT_BY_LOCATION_ID = 'GET_PROJECT_BY_LOCATION_ID'
export const GET_PROJECT_BY_LOCATION_ID_SUCCESS = 'GET_PROJECT_BY_LOCATION_ID_SUCCESS'
export const GET_PROJECT_BY_LOCATION_ID_FAILURE = 'GET_PROJECT_BY_LOCATION_ID_FAILURE'
export const CLEAN_GET_PROJECT_BY_LOCATION_ID = 'CLEAN_GET_PROJECT_BY_LOCATION_ID'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE'

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE'

export const ADD_PRODUCT_POSTED_TO_LIST = 'ADD_PRODUCT_POSTED_TO_LIST'
export const ADD_PRODUCT_POSTED_TO_LIST_SUCCESS = 'ADD_PRODUCT_POSTED_TO_LIST_SUCCESS'
export const ADD_PRODUCT_POSTED_TO_LIST_FAILURE = 'ADD_PRODUCT_POSTED_TO_LIST_FAILURE'

export const DELETE_PRODUCT_POSTED = 'DELETE_PRODUCT_POSTED'
export const DELETE_PRODUCT_POSTED_SUCCESS = 'DELETE_PRODUCT_POSTED_SUCCESS'
export const DELETE_PRODUCT_POSTED_FAILURE = 'DELETE_PRODUCT_POSTED_FAILURE'

export const DELETE_PRODUCT_POSTED_TO_LIST = 'DELETE_PRODUCT_POSTED_TO_LIST'
export const DELETE_PRODUCT_POSTED_TO_LIST_SUCCESS = 'DELETE_PRODUCT_POSTED_TO_LIST_SUCCESS'
export const DELETE_PRODUCT_POSTED_TO_LIST_FAILURE = 'DELETE_PRODUCT_POSTED_TO_LIST_FAILURE'

export const GET_DETAIL_PRODUCT = 'GET_DETAIL_PRODUCT'
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS'
export const GET_DETAIL_PRODUCT_FAILURE = 'GET_DETAIL_PRODUCT_FAILURE'

export const UPDATE_PRODUCT_POSTED = 'UPDATE_PRODUCT_POSTED'
export const UPDATE_PRODUCT_POSTED_SUCCESS = 'UPDATE_PRODUCT_POSTED_SUCCESS'
export const UPDATE_PRODUCT_POSTED_FAILURE = 'UPDATE_PRODUCT_POSTED_FAILURE'

export const UPDATE_PRODUCT_POSTED_TO_LIST = 'UPDATE_PRODUCT_POSTED_TO_LIST'
export const UPDATE_PRODUCT_POSTED_TO_LIST_SUCCESS = 'UPDATE_PRODUCT_POSTED_TO_LIST_SUCCESS'
export const UPDATE_PRODUCT_POSTED_TO_LIST_FAILURE = 'UPDATE_PRODUCT_POSTED_TO_LIST_FAILURE'

export const GET_PRODUCTS_BY_UID = 'GET_PRODUCTS_BY_UID'
export const GET_PRODUCTS_BY_UID_SUCCESS = 'GET_PRODUCTS_BY_UID_SUCCESS'
export const GET_PRODUCTS_BY_UID_FAILURE = 'GET_PRODUCTS_BY_UID_FAILURE'

export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS'
export const UPDATE_USER_INFO_FAILURE = 'UPDATE_USER_INFO_FAILURE'

export const ACTIVE_ACCOUNT = 'ACTIVE_ACCOUNT'
export const ACTIVE_ACCOUNT_SUCCESS = 'ACTIVE_ACCOUNT_SUCCESS'
export const ACTIVE_ACCOUNT_FAILURE = 'ACTIVE_ACCOUNT_FAILURE'

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

export const SEND_EMAIL = 'SEND_EMAIL'
export const SEND_EMAIL_SUCCESS = 'SEND_EMAIL_SUCCESS'
export const SEND_EMAIL_FAILURE = 'SEND_EMAIL_FAILURE'

export const GET_PRODUCTS_FAVOURITE = 'GET_PRODUCTS_FAVOURITE'
export const GET_PRODUCTS_FAVOURITE_SUCCESS = 'GET_PRODUCTS_FAVOURITE_SUCCESS'
export const GET_PRODUCTS_FAVOURITE_FAILURE = 'GET_PRODUCTS_FAVOURITE_FAILURE'

export const ADD_PRODUCT_FAVOURITE = 'ADD_PRODUCT_FAVOURITE'

export const DELETE_PRODUCT_FAVOURITE = 'DELETE_PRODUCT_FAVOURITE'

export const REFRESH_INFO_DETAIL_PRODUCT = 'REFRESH_INFO_DETAIL_PRODUCT'